version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn kickoff_proj.wsgi:application --bind 0.0.0.0:8000
    environment:
      DATABASE_URL: postgres://postgres:hello123@db:5432/my_db
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  postgres_data:
