# Generated by Django 5.2 on 2025-04-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_booking_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
